spring:
  application:
    name: on-store-core
  datasource:
    url: jdbc:postgresql://localhost:5432/on_store_app
    username: postgres
    password: Zxc159753
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  file:
    name: logs/app.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%level] - %msg%n"
interval_in_cron: 0 */15 * * * *
