DROP TABLE IF EXISTS client;

CREATE TABLE client(
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name CHARACTER VARYING NOT NULL,
    surname CHARACTER VARYING NOT NULL,
    patronymic CHARACTER VARYING,
    gender CHARACTER(1) NOT NULL,
    birth_date DATE NOT NULL,
    email CHARACTER VARYING NOT NULL UNIQUE,
    phone CHARACTER VARYING NOT NULL UNIQUE
)